// AUTO-GENERATED by scripts/refresh-workflow-thumbnails.mjs.
// Maps upstream MuAPI thumbnail URLs -> local files in /public/thumbnails/workflows.
// Plain ESM module (no JSON import assertion, no fs) so it bundles cleanly in
// the browser via Turbopack/Webpack/Vite and in Node.

const thumbnailLocalMap = {
  "https://cdn.muapi.ai/workflow-thumbnails/cf0ccf45-f061-41fa-999a-0b7760b5bd32/9de80861-88e6-4511-b6d1-0fe383434b27.jpg": "/thumbnails/workflows/9de80861-88e6-4511-b6d1-0fe383434b27.jpg",
  "https://cdn.muapi.ai/data/2/275585417593/9d1e5efced63471e84c721bc56f3b5e7__1_.jpg": "/thumbnails/workflows/9d1e5efced63471e84c721bc56f3b5e7-1.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/63d42ee7-be47-4bbc-83f0-001d195a263f/44e2daf6-2d0c-450e-8096-a9961ce41dca.jpg": "/thumbnails/workflows/44e2daf6-2d0c-450e-8096-a9961ce41dca.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/a4cc68cb-5870-4f2d-86f5-82a53fbd10b4/ee56fcb2-5e40-4281-a9b7-40e19a86d57c.png": "/thumbnails/workflows/ee56fcb2-5e40-4281-a9b7-40e19a86d57c.png",
  "https://cdn.muapi.ai/workflow-thumbnails/fc3f2c5a-458d-43c9-811e-6a1c93d49061/2ac429a6-40d0-4e72-a657-b540b0287599.jpg": "/thumbnails/workflows/2ac429a6-40d0-4e72-a657-b540b0287599.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/77c8c9db-2790-4e76-b058-50930eae9057/ea8561c7-27e7-45f5-9b34-4aefc92b4853.jpg": "/thumbnails/workflows/ea8561c7-27e7-45f5-9b34-4aefc92b4853.jpg",
  "https://cdn.muapi.ai/data/2/218869843981/d5e1cf2da999468eb8c95c5576f770c0.jpg": "/thumbnails/workflows/d5e1cf2da999468eb8c95c5576f770c0.jpg",
  "https://cdn.muapi.ai/data/2/167746841446/a05a774f9c4b44edbde3c267fc98a8ba.jpg": "/thumbnails/workflows/a05a774f9c4b44edbde3c267fc98a8ba.jpg",
  "https://cdn.muapi.ai/data/2/194206118460/d4b1c9035f624d588a25c0a6a10fa8d4.jpg": "/thumbnails/workflows/d4b1c9035f624d588a25c0a6a10fa8d4.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/3ae4a0a1-42bf-4230-97e5-363e57ffd252/92f35aa2-aa6b-4371-8094-974fdd91cb27.png": "/thumbnails/workflows/92f35aa2-aa6b-4371-8094-974fdd91cb27.png",
  "https://cdn.muapi.ai/workflow-thumbnails/5ffb26a0-4ce2-49c2-b799-9d63c7609d5a/3822baaa-32e3-4aee-ba43-3147f93abe32.png": "/thumbnails/workflows/3822baaa-32e3-4aee-ba43-3147f93abe32.png",
  "https://cdn.muapi.ai/workflow-thumbnails/cfe935c4-705f-4c86-b0ea-efdbac69e293/8e2e8b45-69e6-4b3c-98a2-9eacc3ab6738.jpg": "/thumbnails/workflows/8e2e8b45-69e6-4b3c-98a2-9eacc3ab6738.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/09f6e93a-c5d6-465f-8e8b-a2d286e16332/efb63d81-e15c-4756-8d3b-a7caec863719.jpg": "/thumbnails/workflows/efb63d81-e15c-4756-8d3b-a7caec863719.jpg",
  "https://cdn.muapi.ai/data/2/828782314284/5f85db78e865408d88dc20d5114e7a87.png": "/thumbnails/workflows/5f85db78e865408d88dc20d5114e7a87.png",
  "https://cdn.muapi.ai/workflow-thumbnails/0849ffba-248d-4608-b480-d0a7958d825f/dc9feb33-d456-4c19-ab07-ff489c9d8877.jpg": "/thumbnails/workflows/dc9feb33-d456-4c19-ab07-ff489c9d8877.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/f9d988cf-00e5-49eb-9bdf-d34c7967274d/9a73ddfb-32b6-4c48-a482-d0b1cb41e956.jpg": "/thumbnails/workflows/9a73ddfb-32b6-4c48-a482-d0b1cb41e956.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/e2db61a8-a413-4d1b-bc4c-0c042fba5bf1/ceb77c9f-bc22-4cd2-902d-d114318285bd.jpg": "/thumbnails/workflows/ceb77c9f-bc22-4cd2-902d-d114318285bd.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/9b4b8013-3ffd-4b0f-93b2-2fad8b1a26b2/a5ee433a-8d65-4cdf-86e9-0a2152405898.jpg": "/thumbnails/workflows/a5ee433a-8d65-4cdf-86e9-0a2152405898.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/0fb56847-2334-44d7-ab93-d2318cf3cc28/bdefdd29-1099-4b63-9b73-f5629d21a965.jpg": "/thumbnails/workflows/bdefdd29-1099-4b63-9b73-f5629d21a965.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/0fabec51-5639-4d2c-b388-91aff25bc8a2/14e0bc1d-dd29-4f27-881b-3746399465f5.jpg": "/thumbnails/workflows/14e0bc1d-dd29-4f27-881b-3746399465f5.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/c965b74d-a703-4464-b9ea-97977f1054ab/ace211c7-9878-49c0-9d3a-9c20a2e14aa9.jpg": "/thumbnails/workflows/ace211c7-9878-49c0-9d3a-9c20a2e14aa9.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/44f95b14-7810-4196-9734-513d6d76031c/e1ec38b0-0bfa-4b32-be58-abb88d20509b.jpg": "/thumbnails/workflows/e1ec38b0-0bfa-4b32-be58-abb88d20509b.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/f9a30f99-93a6-467e-a3ee-f4c97577b1b4/e61b479e-2490-44d1-bd00-f6d38896b93a.png": "/thumbnails/workflows/e61b479e-2490-44d1-bd00-f6d38896b93a.png",
  "https://cdn.muapi.ai/workflow-thumbnails/6b41af09-a40f-459f-8179-7ee3a90d300b/2d277bea-1190-4dd2-8252-8716522ada8e.png": "/thumbnails/workflows/2d277bea-1190-4dd2-8252-8716522ada8e.png",
  "https://cdn.muapi.ai/workflow-thumbnails/3e3ecf18-47ef-4c66-aa99-03c51c818950/ef70d6a0-f2a0-463b-9694-31ad65981a1d.jpg": "/thumbnails/workflows/ef70d6a0-f2a0-463b-9694-31ad65981a1d.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/ab3e25bb-ff0e-4df5-9932-b2e1b7e37341/2f09b374-7eb9-4053-a15b-cd8d454ed4fa.jpg": "/thumbnails/workflows/2f09b374-7eb9-4053-a15b-cd8d454ed4fa.jpg",
  "https://cdn.muapi.ai/data/2/213383401706/5ebbaebd7ba644f09925f6e13f271c93.png": "/thumbnails/workflows/5ebbaebd7ba644f09925f6e13f271c93.png",
  "https://cdn.muapi.ai/data/2/149826823732/a26f6bf769b349139684fe3979d152c6.jpg": "/thumbnails/workflows/a26f6bf769b349139684fe3979d152c6.jpg",
  "https://cdn.muapi.ai/data/2/902295592951/abfa2ea772434fc3b08deacd44e0ae01.jpg": "/thumbnails/workflows/abfa2ea772434fc3b08deacd44e0ae01.jpg",
  "https://cdn.muapi.ai/data/2/101502278511/5242c0f5300f403b903e868106f90868.jpg": "/thumbnails/workflows/5242c0f5300f403b903e868106f90868.jpg",
  "https://cdn.muapi.ai/workflow-thumbnails/69a7db7c-2598-44fd-b0d3-ffb1490f8710/87a62412-9eba-46d5-af4d-19b8a46e7e03.png": "/thumbnails/workflows/87a62412-9eba-46d5-af4d-19b8a46e7e03.png",
  "https://cdn.muapi.ai/workflow-thumbnails/ba3bbf0b-cf88-4245-94f6-62fd49f5afde/737ef926-853d-4a50-b769-4b5f5af4c7fe.png": "/thumbnails/workflows/737ef926-853d-4a50-b769-4b5f5af4c7fe.png",
  "https://cdn.muapi.ai/workflow-thumbnails/a81c3c2c-4177-481c-b321-597dbf418278/9bc14ba5-e4e2-455a-8644-4a939b686856.png": "/thumbnails/workflows/9bc14ba5-e4e2-455a-8644-4a939b686856.png",
  "https://cdn.muapi.ai/workflow-thumbnails/2e13c7f0-0273-4ad7-b3dc-966741b08ffa/a0d0afa6-8d8e-47eb-a336-bd088312f0ac.png": "/thumbnails/workflows/a0d0afa6-8d8e-47eb-a336-bd088312f0ac.png",
  "https://cdn.muapi.ai/workflow-thumbnails/7041dd15-cf7a-45bc-83d8-4a8cb414a816/8a1e977e-83dd-41e3-a89c-2cfe60bb1f35.jpg": "/thumbnails/workflows/8a1e977e-83dd-41e3-a89c-2cfe60bb1f35.jpg",
  "https://cdn.muapi.ai/data/2/542121723961/4c6737fb9b114db4b673bc291a751b68.jpg": "/thumbnails/workflows/4c6737fb9b114db4b673bc291a751b68.jpg",
  "https://cdn.muapi.ai/data/2/940819646438/ffa61562e9544b6c83cc3607e1429483.jpg": "/thumbnails/workflows/ffa61562e9544b6c83cc3607e1429483.jpg",
  "https://cdn.muapi.ai/data/2/943308397627/c1929cd981dd46ada5884b0b2228696d.jpg": "/thumbnails/workflows/c1929cd981dd46ada5884b0b2228696d.jpg",
  "https://d3adwkbyhxyrtq.cloudfront.net/data/186/816557014682/08b8e45280c6470f9931260909540e12.jpg": "/thumbnails/workflows/08b8e45280c6470f9931260909540e12.jpg",
  "https://cdn.muapi.ai/data/151566/664153413026/Sin_titulo-2gdf.png": "/thumbnails/workflows/sin-titulo-2gdf.png",
  "https://cdn.muapi.ai/assets/demos/3283a83b5e374ca781f298b04a9e7640.png": "/thumbnails/workflows/3283a83b5e374ca781f298b04a9e7640.png",
  "https://cdn.muapi.ai/data/8653/438030516028/20260527_093505.jpg": "/thumbnails/workflows/20260527-093505.jpg",
  "https://cdn.muapi.ai/data/63638/494348809260/naruto-guy-a.png": "/thumbnails/workflows/naruto-guy-a.png",
  "https://d3adwkbyhxyrtq.cloudfront.net/webassets/videomodels/wan2.6-text-to-image.png": "/thumbnails/workflows/wan2-6-text-to-image.png",
  "https://cdn.muapi.ai/data/68426/545547338092/WhatsApp_Image_2026-06-01_at_00.42.17.jpeg": "/thumbnails/workflows/whatsapp-image-2026-06-01-at-00-42-17.jpg",
  "https://cdn.muapi.ai/data/22562/673683673317/Sukh_Prohor-Tirtho_Mozumder-4696e-550383_upscayl_5x_upscayl-standard-4x.png": "/thumbnails/workflows/sukh-prohor-tirtho-mozumder-4696e-550383-upscayl-5x-upscayl-standard-4x.png",
};

export function rewriteThumbnail(url) {
  if (!url || typeof url !== 'string') return url;
  if (url.startsWith('/')) return url;
  if (thumbnailLocalMap[url]) return thumbnailLocalMap[url];
  return `/api/thumbnail?url=${encodeURIComponent(url)}`;
}

export function rewriteThumbnails(list) {
  if (!Array.isArray(list)) return list;
  return list.map((item) => {
    if (!item || typeof item !== 'object') return item;
    let next = item;
    if (item.thumbnail) {
      next = { ...next, thumbnail: rewriteThumbnail(item.thumbnail) };
    }
    if (item.icon_url) {
      next = { ...next, icon_url: rewriteThumbnail(item.icon_url) };
    }
    return next;
  });
}

