/**
 * Seed thumbnails for fresh installs and offline fallbacks.
 *
 * Each entry follows the GeneratedImage shape used by ImageGallery,
 * so seed items render identically to real generated images.
 */

import type { GeneratedImage } from './types'

export const SEED_THUMBNAILS: GeneratedImage[] = [
  {
    id: 'seed-gaming-1',
    url: '/thumbnails/seed-gaming-1.jpeg',
    prompt: 'Epic gaming thumbnail, shocked face reaction, bold title text, dramatic lighting, vibrant colors, high energy',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'cinematic',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'seed-finance-1',
    url: '/thumbnails/seed-finance-1.jpeg',
    prompt: 'Finance YouTube thumbnail, money symbols, professional suit, clean background, trust-inspiring design',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'vibrant',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'seed-tutorial-1',
    url: '/thumbnails/seed-tutorial-1.jpeg',
    prompt: 'Clean tutorial thumbnail, step-by-step arrows, professional look, clear text overlay, modern design',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'minimal',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'seed-reaction-1',
    url: '/thumbnails/seed-reaction-1.jpeg',
    prompt: 'Reaction video thumbnail, exaggerated facial expression, bright background, emotion-focused',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'vibrant',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'seed-ai-1',
    url: '/thumbnails/seed-ai-1.jpeg',
    prompt: 'Futuristic AI YouTube thumbnail, glowing neural network or hologram overlay, sleek tech aesthetic',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'neon',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: 'seed-marketing-1',
    url: '/thumbnails/seed-marketing-1.jpeg',
    prompt: 'Bold marketing YouTube thumbnail, charismatic presenter expression, growth chart or product showcase',
    model: 'gpt-image-2',
    quality: 'medium',
    format: 'jpeg',
    style: 'bold-text',
    aspectRatio: '16:9',
    width: 1280,
    height: 720,
    isPublic: true,
    createdAt: new Date(Date.now() - 518400000).toISOString(),
  },
]
