export const PRODUCT_NAME = 'SmartVideo GO';

export const NAV_ITEMS = [
  { label: 'Demos', href: '#demos' },
  { label: 'Workflow', href: '#workflow' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'FAQ', href: '#faq' }
];

export const LOGOS = [
  'Creators', 'Agencies', 'Video Teams', 'UGC Brands', 'AI Studios', 'Enterprise'
];

export const FEATURES = [
  { id: 'image', label: 'Image Studio', eyebrow: 'Generative images', title: 'Prompt-to-image studio', description: 'Turn a prompt into a polished image using 200+ models with style and aspect-ratio controls.', promptLabel: 'Describe the image', defaultPrompt: 'A futuristic wellness app dashboard floating above a calm city skyline', options: ['Flux Pro', '1024x1024', 'Photoreal', 'Fast'], outputLabel: 'Generated image brief', outputMode: 'image', eta: '12s', ctaPath: '/studio/image', stats: ['200+ models', 'T2I + I2I', 'HD output'] },
  { id: 'video', label: 'Video Studio', eyebrow: 'Text-to-video', title: 'Cinematic video generation', description: 'Create short videos from prompts, reference frames, camera moves, and model settings.', promptLabel: 'Describe the video', defaultPrompt: 'A product reveal shot with soft light, slow camera push, and premium motion', options: ['Veo 3', '16:9', '5s', 'Cinematic'], outputLabel: 'Generated video plan', outputMode: 'video', eta: '45s', ctaPath: '/studio/video', stats: ['T2V', 'I2V', 'V2V'] },
  { id: 'audio', label: 'Audio Studio', eyebrow: 'Sound design', title: 'Text-to-audio and music', description: 'Generate soundscapes, voiceover concepts, and music beds for social and product videos.', promptLabel: 'Describe the sound', defaultPrompt: 'Warm uplifting synth bed with soft percussion for a SaaS product trailer', options: ['Music', 'Voiceover', '30s', 'Stereo'], outputLabel: 'Generated audio concept', outputMode: 'audio', eta: '18s', ctaPath: '/studio/audio', stats: ['TTS', 'SFX', 'Music'] },
  { id: 'clipping', label: 'AI Clipping', eyebrow: 'Repurpose video', title: 'Long-form to short-form clips', description: 'Find hooks, summarize moments, and package clips for TikTok, Reels, Shorts, and ads.', promptLabel: 'Paste the video topic', defaultPrompt: 'A founder interview about using AI to launch faster', options: ['TikTok', 'Hook-first', 'Captions', '9:16'], outputLabel: 'Generated clip package', outputMode: 'clip', eta: '22s', ctaPath: '/studio/clipping', stats: ['Hooks', 'Captions', 'Exports'] },
  { id: 'vibe-motion', label: 'Vibe Motion', eyebrow: 'Visual motion', title: 'Animate stills with vibe motion', description: 'Add controlled camera movement, parallax, and cinematic motion to static images.', promptLabel: 'Describe the motion', defaultPrompt: 'Slow parallax over a luxury skincare product with warm highlights', options: ['Parallax', 'Slow push', '9:16', 'High'], outputLabel: 'Generated motion brief', outputMode: 'motion', eta: '28s', ctaPath: '/studio/vibe-motion', stats: ['Motion', 'Parallax', 'Loops'] },
  { id: 'lipsync', label: 'Lip Sync', eyebrow: 'Character animation', title: 'Sync faces to audio', description: 'Pair a character image with a voiceover to produce a lip-synced video preview.', promptLabel: 'Describe the character and line', defaultPrompt: 'A friendly host introduces a new AI video tool in a confident tone', options: ['Host', 'English', '30s', 'Natural'], outputLabel: 'Generated lip-sync plan', outputMode: 'lipsync', eta: '35s', ctaPath: '/studio/lipsync', stats: ['Face sync', 'Voice', 'Export'] },
  { id: 'cinema', label: 'Cinema Studio', eyebrow: 'Film controls', title: 'Director-grade camera language', description: 'Control lens, aperture, focal length, camera move, and scene tone before generation.', promptLabel: 'Describe the scene', defaultPrompt: 'A hero walks through neon rain toward a glowing portal', options: ['35mm', 'f/2.8', 'Dolly in', 'Neo-noir'], outputLabel: 'Generated shot plan', outputMode: 'cinema', eta: '40s', ctaPath: '/studio/cinema', stats: ['Camera', 'Lens', 'Scene'] },
  { id: 'marketing', label: 'Marketing Studio', eyebrow: 'Campaign assets', title: 'Generate campaign-ready assets', description: 'Create ad copy, hooks, thumbnails, and video concepts from one product brief.', promptLabel: 'Describe the product', defaultPrompt: 'An AI video platform for creators who need fast campaign assets', options: ['Ad campaign', '3 hooks', 'UGC style', 'CTA'], outputLabel: 'Generated campaign brief', outputMode: 'marketing', eta: '15s', ctaPath: '/studio/marketing', stats: ['Hooks', 'Ads', 'Briefs'] },
  { id: 'recast', label: 'Body Swap', eyebrow: 'Character replacement', title: 'Swap bodies in video', description: 'Replace the character in any video by uploading a source clip and a character image.', promptLabel: 'Describe the motion', defaultPrompt: 'Swap the person in this video with a different character while preserving the motion', options: ['Kling', 'Runway', '16:9', 'HD'], outputLabel: 'Generated swap plan', outputMode: 'recast', eta: '38s', ctaPath: '/studio/recast', stats: ['Body swap', 'Motion', 'Render'] },
  { id: 'workflows', label: 'Workflows', eyebrow: 'Automation', title: 'Reusable creative pipelines', description: 'Build repeatable AI production workflows from prompt, generation, review, and export nodes.', promptLabel: 'Describe the workflow', defaultPrompt: 'Turn a script into storyboard frames, generated video clips, captions, and export', options: ['Script', 'Storyboard', 'Video', 'Export'], outputLabel: 'Generated workflow map', outputMode: 'workflow', eta: '10s', ctaPath: '/studio/workflows', stats: ['Nodes', 'Templates', 'Runs'] },
  { id: 'agents', label: 'Agents', eyebrow: 'Conversational AI', title: 'Custom AI agents', description: 'Create and chat with agents that help write, plan, edit, and operate your studio.', promptLabel: 'Ask the agent', defaultPrompt: 'Create a launch checklist for a new AI video product', options: ['Planning', 'Research', 'Checklist', 'Concise'], outputLabel: 'Generated agent response', outputMode: 'agent', eta: '8s', ctaPath: '/studio/agents', stats: ['Chat', 'Memory', 'Tools'] },
  { id: 'design-agent', label: 'Design Agent', eyebrow: 'Visual design', title: 'AI-assisted design workspace', description: 'Generate layout direction, visual systems, and design tasks through an agent workflow.', promptLabel: 'Describe the design goal', defaultPrompt: 'Design a premium landing page for an AI video SaaS', options: ['Landing page', 'Dark UI', 'High contrast', 'SaaS'], outputLabel: 'Generated design direction', outputMode: 'design', eta: '14s', ctaPath: '/studio/design-agent', stats: ['Layout', 'System', 'Tasks'] },
  { id: 'videco', label: 'Videco', eyebrow: 'Video operations', title: 'Video marketing command center', description: 'Manage generated videos, campaigns, analytics, leads, feedback, and embeds in one workspace.', promptLabel: 'Describe the campaign', defaultPrompt: 'Launch a creator-led campaign for an AI video tool with weekly analytics', options: ['Campaign', 'Analytics', 'Leads', 'Embed'], outputLabel: 'Generated campaign dashboard', outputMode: 'videco', eta: '12s', ctaPath: '/studio/videco', stats: ['Library', 'Leads', 'Insights'] },
  { id: 'vfx-studio', label: 'VFX Studio', eyebrow: 'AI effects', title: 'Add visual effects to footage', description: 'Choose AI effects, motion controls, and VFX settings to transform source media.', promptLabel: 'Describe the VFX shot', defaultPrompt: 'Add glowing energy trails and camera shake to a product launch clip', options: ['Energy', 'Motion blur', '480p', 'High'], outputLabel: 'Generated VFX brief', outputMode: 'vfx', eta: '38s', ctaPath: '/studio/vfx-studio', stats: ['Effects', 'Motion', 'Render'] },
  { id: 'storyboard', label: 'Storyboard', eyebrow: 'Pre-production', title: 'Script-to-scene storyboard', description: 'Break a script into scenes, shots, visual notes, and editable storyboard cards.', promptLabel: 'Paste the script', defaultPrompt: 'A founder discovers an AI tool that turns ideas into launch videos', options: ['6 scenes', 'Shot list', 'Visual notes', 'Edit'], outputLabel: 'Generated storyboard', outputMode: 'storyboard', eta: '16s', ctaPath: '/studio/storyboard', stats: ['Scenes', 'Shots', 'Notes'] },
  { id: 'scene-planner', label: 'Scene Planner', eyebrow: 'Workflow builder', title: 'Plan scenes and nodes', description: 'Map a scene or production workflow with prompt, generation, review, and output nodes.', promptLabel: 'Describe the scene plan', defaultPrompt: 'A three-scene launch video with product closeups and founder voiceover', options: ['3 nodes', 'Prompt', 'Video', 'Output'], outputLabel: 'Generated scene plan', outputMode: 'scene', eta: '12s', ctaPath: '/studio/scene-planner', stats: ['Nodes', 'Templates', 'History'] },
  { id: 'music-studio', label: 'Music Studio', eyebrow: 'Original audio', title: 'Generate music and sound beds', description: 'Create short music concepts with mood, duration, and style controls.', promptLabel: 'Describe the track', defaultPrompt: 'A confident electronic track for a product demo video', options: ['Electronic', '45s', 'Loopable', 'Clean'], outputLabel: 'Generated music concept', outputMode: 'audio', eta: '18s', ctaPath: '/studio/music-studio', stats: ['Tracks', 'Mood', 'Loop'] },
  { id: 'thumbnail-studio', label: 'Thumbnail Studio', eyebrow: 'Click-worthy art', title: 'Create video thumbnails', description: 'Generate thumbnails with style, model, and text treatment controls for every video.', promptLabel: 'Describe the thumbnail', defaultPrompt: 'A bold thumbnail for an AI video tool with a creator and glowing dashboard', options: ['Bold', 'Creator', '16:9', 'High CTR'], outputLabel: 'Generated thumbnail concept', outputMode: 'thumbnail', eta: '14s', ctaPath: '/studio/thumbnail-studio', stats: ['CTR', 'Styles', 'Text'] },
  { id: 'script-writer', label: 'Script Writer', eyebrow: 'Copy generation', title: 'Write scripts and ad copy', description: 'Generate scripts, hooks, voiceover lines, and content variations from a product brief.', promptLabel: 'Describe the script', defaultPrompt: 'A 30-second ad script for an AI video platform', options: ['Ad script', '30s', 'UGC', 'Persuasive'], outputLabel: 'Generated script', outputMode: 'script', eta: '8s', ctaPath: '/studio/script-writer', stats: ['Hooks', 'Scripts', 'Variants'] },
  { id: 'presentation', label: 'Presentation', eyebrow: 'Decks', title: 'Turn ideas into presentations', description: 'Create presentation outlines, slide copy, and speaker notes from a topic.', promptLabel: 'Describe the presentation', defaultPrompt: 'A sales deck for an AI video platform targeting marketing teams', options: ['Sales deck', '8 slides', 'Executive', 'CTA'], outputLabel: 'Generated presentation outline', outputMode: 'presentation', eta: '10s', ctaPath: '/studio/presentation', stats: ['Slides', 'Outline', 'Notes'] },
  { id: 'content-planner', label: 'Content Planner', eyebrow: 'Editorial planning', title: 'Plan content calendars', description: 'Generate campaign ideas, post angles, formats, and publishing cadence.', promptLabel: 'Describe the content goal', defaultPrompt: 'A two-week content calendar for launching an AI video product', options: ['2 weeks', 'Social', 'Educational', 'Launch'], outputLabel: 'Generated content plan', outputMode: 'content', eta: '9s', ctaPath: '/studio/content-planner', stats: ['Calendar', 'Angles', 'Cadence'] },
  { id: 'apps', label: 'Explore Apps', eyebrow: 'App library', title: 'Browse every studio app', description: 'Open the full app library and jump into any creative studio from one launchpad.', promptLabel: 'What do you want to build?', defaultPrompt: 'Show me the best apps for creating a product launch video', options: ['Launch video', 'Ads', 'Social', 'Explore'], outputLabel: 'Generated app recommendations', outputMode: 'apps', eta: '6s', ctaPath: '/studio/apps', stats: ['20+ apps', 'Tabs', 'Deep links'] }
];

export const TESTIMONIALS = [
  { quote: 'The landing page needs to feel like the product itself: fast, visual, and impossible to ignore.', name: 'Creative operations lead', role: 'Agency producer' },
  { quote: 'Every feature should be demoable without a login, but every demo should point toward the full studio.', name: 'Growth marketer', role: 'SaaS launch team' },
  { quote: 'The best AI tools sell through interaction, not static screenshots.', name: 'Founder', role: 'AI video platform' }
];

export const PRICING = [
  {
    name: 'Pro',
    price: '$299',
    badge: 'Lifetime',
    description: 'One-time payment. Unlock every studio, forever.',
    features: FEATURES.map((f) => f.label)
  }
];

export const FAQS = [
  { question: 'Do the landing page demos require an API key?', answer: 'No. The landing page demos are local, deterministic previews. The full studio keeps the existing API-key and proxy behavior.' },
  { question: 'Will the full studio still work?', answer: 'Yes. The landing page replaces only the root redirect and links to /studio/<feature-id> for the full experience.' },
  { question: 'Are the demos connected to generation APIs?', answer: 'No. They simulate the interaction pattern and output so the page stays fast, reliable, and available without credentials.' }
];
