export const PRODUCT_NAME = 'SmartVideo GO';

export const NAV_ITEMS = [
  { label: 'Studio', href: '#studio' },
  { label: 'Workflow', href: '#workflow' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'FAQ', href: '#faq' }
];

export const LOGOS = [
  'Creators', 'Agencies', 'Video Teams', 'UGC Brands', 'AI Studios', 'Enterprise'
];

export const FEATURES = [
  { id: 'image', label: 'Image Studio', eyebrow: 'Text & image to image', title: 'Text-to-image and image-to-image', description: 'Text-to-image and image-to-image generation with 74+ models, multi-image reference input (up to 14 images), and inpainting.', promptLabel: 'Describe the image', defaultPrompt: 'A futuristic wellness app dashboard floating above a calm city skyline', options: ['Flux Pro', '74+ models', 'Inpainting', '14 refs'], outputLabel: 'Generated image brief', outputMode: 'image', eta: '12s', ctaPath: '/studio/image', stats: ['74+ models', 'T2I + I2I', 'Inpainting'] },
  { id: 'video', label: 'Video Studio', eyebrow: 'Text, image & video to video', title: 'Cinematic video generation', description: 'Text-to-video, image-to-video, and video-to-video generation across 230+ models with motion control.', promptLabel: 'Describe the video', defaultPrompt: 'A product reveal shot with soft light, slow camera push, and premium motion', options: ['Veo 3', '230+ models', 'Motion control', '16:9'], outputLabel: 'Generated video plan', outputMode: 'video', eta: '45s', ctaPath: '/studio/video', stats: ['230+ models', 'T2V + I2V + V2V', 'Motion control'] },
  { id: 'audio', label: 'Audio Studio', eyebrow: 'Music, voice & sound', title: 'AI music, voice, and sound', description: 'AI music, voice, and sound generation via Suno, Minimax, ElevenLabs, and MMAudio — with a built-in premium audio player.', promptLabel: 'Describe the sound', defaultPrompt: 'Warm uplifting synth bed with soft percussion for a SaaS product trailer', options: ['Suno', 'Minimax', 'ElevenLabs', 'MMAudio'], outputLabel: 'Generated audio concept', outputMode: 'audio', eta: '18s', ctaPath: '/studio/audio', stats: ['Suno', 'ElevenLabs', 'Premium player'] },
  { id: 'clipping', label: 'AI Clipping', eyebrow: 'Highlight extraction', title: 'Auto viral highlight clips', description: 'Extracts viral highlight clips and timing markers from long-form videos automatically.', promptLabel: 'Paste the video topic', defaultPrompt: 'A founder interview about using AI to launch faster', options: ['TikTok', 'Hook-first', 'Captions', '9:16'], outputLabel: 'Generated clip package', outputMode: 'clip', eta: '22s', ctaPath: '/studio/clipping', stats: ['Highlights', 'Timing markers', 'Auto'] },
  { id: 'vibe-motion', label: 'Vibe Motion', eyebrow: 'Animated motion graphics', title: 'Kinetic motion graphics', description: 'Generates and remixes animated motion graphics (kinetic typography, charts, logo reveals) from text prompts.', promptLabel: 'Describe the motion', defaultPrompt: 'Animated kinetic typography reveal with bold gradient charts for a product launch', options: ['Kinetic type', 'Charts', 'Logo reveal', '9:16'], outputLabel: 'Generated motion brief', outputMode: 'motion', eta: '28s', ctaPath: '/studio/vibe-motion', stats: ['Kinetic type', 'Charts', 'Logo reveals'] },
  { id: 'lipsync', label: 'Lip Sync Studio', eyebrow: 'Talking video', title: 'Portraits & avatars that talk', description: 'Turns portraits, video, or avatars into talking videos synced to audio, using 14 models across image, video, and avatar modes.', promptLabel: 'Describe the character and line', defaultPrompt: 'A friendly host introduces a new AI video tool in a confident tone', options: ['Image', 'Video', 'Avatar', '14 models'], outputLabel: 'Generated lip-sync plan', outputMode: 'lipsync', eta: '35s', ctaPath: '/studio/lipsync', stats: ['14 models', 'Image / Video / Avatar', 'Audio sync'] },
  { id: 'cinema', label: 'Cinema Studio', eyebrow: 'Photoreal stills', title: 'Director-grade camera control', description: 'Produces photorealistic cinematic stills with director-grade virtual camera controls (camera bodies, lenses, focal lengths, apertures).', promptLabel: 'Describe the scene', defaultPrompt: 'A hero walks through neon rain toward a glowing portal', options: ['35mm', 'f/2.8', 'Dolly in', 'Neo-noir'], outputLabel: 'Generated shot plan', outputMode: 'cinema', eta: '40s', ctaPath: '/studio/cinema', stats: ['Camera bodies', 'Lenses', 'Apertures'] },
  { id: 'storyboard', label: 'Storyboard', eyebrow: 'Multi-scene planning', title: 'Plan scenes & shots', description: 'Multi-scene storyboard planner with characters, episodes, and AI-generated shots including camera/angle controls.', promptLabel: 'Paste the script', defaultPrompt: 'A founder discovers an AI tool that turns ideas into launch videos', options: ['Scenes', 'Characters', 'Episodes', 'Camera / angle'], outputLabel: 'Generated storyboard', outputMode: 'storyboard', eta: '16s', ctaPath: '/studio/storyboard', stats: ['Scenes', 'Characters', 'Camera control'] },
  { id: 'marketing', label: 'Marketing Studio', eyebrow: 'High-converting ads', title: 'AI video ads', description: 'Generates high-converting AI video ads with selectable avatars, templates, and product images.', promptLabel: 'Describe the product', defaultPrompt: 'An AI video platform for creators who need fast campaign assets', options: ['Avatars', 'Templates', 'Product image', 'CTA'], outputLabel: 'Generated campaign brief', outputMode: 'marketing', eta: '15s', ctaPath: '/studio/marketing', stats: ['Avatars', 'Templates', 'Product images'] },
  { id: 'recast', label: 'Body Swap (Recast)', eyebrow: 'Character replacement', title: 'Swap characters, keep motion', description: 'Swaps the character in any video while preserving the original motion (Kling / Runway recast).', promptLabel: 'Describe the motion', defaultPrompt: 'Swap the person in this video with a different character while preserving the motion', options: ['Kling', 'Runway', '16:9', 'HD'], outputLabel: 'Generated swap plan', outputMode: 'video', eta: '38s', ctaPath: '/studio/recast', stats: ['Body swap', 'Motion preserved', 'Kling / Runway'] },
  { id: 'workflows', label: 'Workflow Studio', eyebrow: 'Visual pipelines', title: 'Node-based builder', description: 'Node-based, drag-and-drop builder for multi-step AI pipelines, with templates, community workflows, a playground, and API execution.', promptLabel: 'Describe the workflow', defaultPrompt: 'Turn a script into storyboard frames, generated video clips, captions, and export', options: ['Drag & drop', 'Templates', 'Playground', 'API'], outputLabel: 'Generated workflow map', outputMode: 'workflow', eta: '10s', ctaPath: '/studio/workflows', stats: ['Nodes', 'Community', 'API exec'] },
  { id: 'agents', label: 'Agents', eyebrow: 'Conversational AI', title: 'Browse & chat with agents', description: 'Browse and chat with template and user-created AI agents across a gallery, your agents, and conversation history.', promptLabel: 'Ask the agent', defaultPrompt: 'Create a launch checklist for a new AI video product', options: ['Gallery', 'Your agents', 'History', 'Templates'], outputLabel: 'Generated agent response', outputMode: 'agent', eta: '8s', ctaPath: '/studio/agents', stats: ['Gallery', 'Your agents', 'History'] },
  { id: 'design-agent', label: 'Design Agent', eyebrow: 'AI creative assistant', title: 'Chat-based "Go-AI"', description: 'AI Chat-based autonomous creative assistant ("Go-AI") with 33 built-in templates for logos, ads, mockups, posters, and more.', promptLabel: 'Describe the design goal', defaultPrompt: 'Design a premium landing page for an AI video SaaS', options: ['Logos', 'Ads', 'Mockups', 'Posters'], outputLabel: 'Generated design direction', outputMode: 'design', eta: '14s', ctaPath: '/studio/design-agent', stats: ['33 templates', 'Logos', 'Ads'] },
  { id: 'vfx-studio', label: 'VFX Studio', eyebrow: 'AI effects', title: 'Effects & motion control', description: 'Applies AI effects, motion-control camera shots, and VFX (Levitate, Explosions, 360 Orbit, etc.) to video or image.', promptLabel: 'Describe the VFX shot', defaultPrompt: 'Add glowing energy trails and camera shake to a product launch clip', options: ['Levitate', 'Explosions', '360 Orbit', 'Motion ctrl'], outputLabel: 'Generated VFX brief', outputMode: 'vfx', eta: '38s', ctaPath: '/studio/vfx-studio', stats: ['Effects', 'Motion control', 'VFX'] },
  { id: 'thumbnail-studio', label: 'Thumbnail Studio', eyebrow: 'CTR-optimized art', title: 'YouTube thumbnails', description: 'Creates CTR-optimized YouTube thumbnails with a CTR prompt engine, style presets, category templates, and a community gallery.', promptLabel: 'Describe the thumbnail', defaultPrompt: 'A bold thumbnail for an AI video tool with a creator and glowing dashboard', options: ['CTR engine', 'Style presets', 'Category', 'Gallery'], outputLabel: 'Generated thumbnail concept', outputMode: 'thumbnail', eta: '14s', ctaPath: '/studio/thumbnail-studio', stats: ['CTR engine', 'Style presets', 'Gallery'] },
  { id: 'ai-influencer', label: 'AI Influencer Studio', eyebrow: 'Consistent characters', title: 'Build AI influencers', description: 'Builds consistent AI-influencer/character portraits via a hierarchical attribute builder (nano-banana-pro).', promptLabel: 'Describe the character', defaultPrompt: 'A consistent lifestyle AI influencer with a signature look across portrait sets', options: ['nano-banana-pro', 'Attribute builder', 'Consistent', 'Portraits'], outputLabel: 'Generated character portrait', outputMode: 'image', eta: '30s', ctaPath: '/studio/ai-influencer', stats: ['Consistent', 'Attribute builder', 'nano-banana-pro'] },
  { id: 'social-publishing', label: 'Social Publishing', eyebrow: 'Direct publishing', title: 'Publish to socials', description: 'Publishes generated media directly to YouTube, Instagram, and TikTok with per-platform options and publish history.', promptLabel: 'What do you want to publish?', defaultPrompt: 'Publish the new product launch video to YouTube, Instagram, and TikTok', options: ['YouTube', 'Instagram', 'TikTok', 'History'], outputLabel: 'Publish summary', outputMode: 'social', eta: '12s', ctaPath: '/studio/social-publishing', stats: ['YouTube', 'Instagram', 'TikTok'] }
];

export const TESTIMONIALS = [
  { quote: 'The landing page needs to feel like the product itself: fast, visual, and impossible to ignore.', name: 'Creative operations lead', role: 'Agency producer' },
  { quote: 'Every feature should be demoable without a login, but every demo should point toward the full studio.', name: 'Growth marketer', role: 'SaaS launch team' },
  { quote: 'The best AI tools sell through interaction, not static screenshots.', name: 'Founder', role: 'AI video platform' }
];

export const PRICING = [
  { name: 'Starter', price: 'Free', description: 'Try the studio and export lightweight previews.', features: ['Interactive landing demos', 'Studio preview access', 'Community generation limits'] },
  { name: 'Pro', price: '$29', description: 'For creators and teams shipping weekly AI video campaigns.', features: ['Full studio access', 'Priority generation queue', 'Campaign and workflow tools'] },
  { name: 'Studio', price: 'Custom', description: 'For agencies and enterprise teams with volume and workflow needs.', features: ['Team seats', 'Custom workflows', 'Priority support'] }
];

export const FAQS = [
  { question: 'Are the landing page demos the real studio?', answer: 'Yes. Each "Use demo" button opens the actual studio interface for that feature — the same UI, models, and controls used in the full app. No mockups or fake previews.' },
  { question: 'Will the full studio still work?', answer: 'Yes. The landing page links to /studio/<feature-id> for the full experience, and the in-page demos reuse the exact same studio components.' },
  { question: 'Do the demos need an API key to generate?', answer: 'The studio UI loads without a key. If you have a MuAPI key saved in the studio, generation works inside the demo too; otherwise enter your key in the studio settings to run a generation.' }
];
