// AUTO-GENERATED by ingest script
// Source: https://github.com/HuyLe82US/awesome-seedance-prompts
// Only entries with BOTH a video AND an English prompt are included.

import { type VideoDemo } from './types';
export { DEMO_CATEGORIES } from './types';

export const SEEDANCE_PROMPTS_DEMOS: VideoDemo[] = [

];

export const HERO_DEMO_SP = SEEDANCE_PROMPTS_DEMOS.find((d) => d.hero);
export const INTERACTIVE_DEMO_SP = SEEDANCE_PROMPTS_DEMOS.find((d) => d.interactive);
export const FEATURED_SP = SEEDANCE_PROMPTS_DEMOS.filter((d) => d.featured);
