// AUTO-GENERATED by ingest script
// Source: https://github.com/ZeroLu/awesome-seedance
// Only entries with BOTH a video AND an English prompt are included.

import { type VideoDemo } from './types';
export { DEMO_CATEGORIES } from './types';

export const SEEDANCE_1_DEMOS: VideoDemo[] = [
{
    "id": 1,
    "slug": "hollywood-professional-racing-movie-style",
    "title": "Hollywood Professional Racing Movie Style",
    "category": "Cinema",
    "rawCategory": "Cinematic Film Styles",
    "useCase": "Cinematic Film Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/hollywood-professional-racing-movie-style.mp4",
    "posterSrc": "/media/seedance-1/previews/hollywood-professional-racing-movie-style.svg",
    "prompt": "Style: Hollywood Professional Racing Movie (Le Mans Style), Cinematic Night, Rain, High Stakes Sport.\nDuration: 15s.\n\n[00-05s] Shot 1: The Veteran (Interior/Close-up).\nRain lashes the windshield of a high-tech race car on a track. The Veteran driver (in helmet) looks over, calm and focused. Dashboard lights reflect on his visor.\nDialogue Cue: He gives a subtle nod and mouths \"Let's go.\"\n\n[05-10s] Shot 2: The Challenger (Interior/Close-up).\nCut to the rival car next to him. The younger driver grips the wheel tight, breathing heavily. Eyes wide with adrenaline.\nDialogue Cue: He whispers \"Focus\" to himself.\n\n[10-15s] Shot 3: The Green Light (Wide Action).\nThe starting lights turn Green. Both cars accelerate in perfect sync on the wet asphalt. Water sprays massively into the camera lens. Motion blur turns the stadium lights into long streaks of color.",
    "featured": true,
    "hero": true,
    "interactive": false,
    "studioTab": "cinema",
    "tags": [
      "cinematic film styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 2,
    "slug": "denis-villeneuve-style-epic-desert-scene",
    "title": "Denis Villeneuve Style Epic Desert Scene",
    "category": "Cinema",
    "rawCategory": "Cinematic Film Styles",
    "useCase": "Cinematic Film Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/denis-villeneuve-style-epic-desert-scene.mp4",
    "posterSrc": "/media/seedance-1/previews/denis-villeneuve-style-epic-desert-scene.svg",
    "prompt": "Style: IMAX 70mm Film, Denis Villeneuve Style, Gritty Realism, Epic Scale, Desaturated.\nDuration: 15s.\n[00-05s] Extreme Wide Shot (The Scale). A colossal sandstorm, miles high, swallows a vast desert landscape. A tiny convoy of armored military vehicles races away from it. The scale of nature vs man is terrifying. Hans Zimmer style tension.\n[05-10s] Cockpit Cam (The Panic). Inside the lead rover. The pilot screams \"GO! GO!\" (Subtitle: MAX POWER!). Camera shakes violently. Sand blasts the windshield. The sun is blocked out by the approaching wall of dust.\n[10-15s] The Jump (The Climax). The rover hits a massive dune and launches into the air (Slow Motion). Silhouette against the dark storm. Lightning strikes within the dust cloud. Debris flies past the lens. Cut to black on impact.",
    "featured": false,
    "hero": false,
    "interactive": true,
    "studioTab": "cinema",
    "tags": [
      "cinematic film styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 3,
    "slug": "wong-kar-wai-film-style-rainy-phone-booth-scene",
    "title": "Wong Kar-wai Film Style (Rainy Phone Booth Scene)",
    "category": "Cinema",
    "rawCategory": "Cinematic Film Styles",
    "useCase": "Cinematic Film Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/wong-kar-wai-film-style-rainy-phone-booth-scene.mp4",
    "posterSrc": "/media/seedance-1/previews/wong-kar-wai-film-style-rainy-phone-booth-scene.svg",
    "prompt": "[Film Style]: 90s Hong Kong Art Cinema style, retro film feel, high ISO grain, ambiguous yellow-green tint, frame stepping effect, melancholic atmosphere.\n\n[Core Dialogue (for emotion control)]: \"If memories were canned food, I hope they never expire.\"\n\n[Video Duration]: 10 seconds\n[Script]:\n\n[00:00-00:04] Shot 1: Through the Glass Peeping.\nScene: A rain-covered red public telephone booth.\nCharacter: A man (or woman) in a khaki trench coat holding the receiver tightly, not speaking, just listening.\nEmotional Performance: Through the glass refraction, see his/her eyes hollow yet deeply emotional. Rain flows down the glass, distorting his face like an oil painting.\nSubtitle/Narrative sense: The picture seems frozen, only the sound of rain.\n\n[00:04-00:07] Shot 2: Extreme Close-up & Micro-expression.\nScene: Focus on the character's lips and half face.\nAction: He/She whispers softly into the receiver. Lips tremble slightly, seeming to want to say something but swallow it back.\nLighting: Street neon bokeh flows across his face, bright and dim alternately.\nDialogue Emotion Mapping: Shows the ultimate restraint and loneliness of \"wanting to touch but drawing back\".\n\n[00:07-00:10] Shot 3: Signature Slow-shutter Drag Shadow.\nScene: Character hangs up phone, turns around and walks into the rainy crowd.\nVisual Effect: Using frame stepping effect (stop-motion feel), the character's back becomes blurred with trailing shadows (motion blur), as if the soul stayed in place while only the body walks away.\nEnvironment: Background is flowing city car lights forming elongated light trails.\n\n[Technical Parameters]: Simulated handheld camera, shallow depth of field, color shift, emotionally intense.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "cinema",
    "tags": [
      "cinematic film styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 4,
    "slug": "muji-brand-promotional-video",
    "title": "MUJI Brand Promotional Video",
    "category": "Commercial",
    "rawCategory": "Advertising & Commercial Branding",
    "useCase": "Advertising & Commercial Branding",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/muji-brand-promotional-video.mp4",
    "posterSrc": "/media/seedance-1/previews/muji-brand-promotional-video.svg",
    "prompt": "Help me generate a promotional video about the MUJI brand.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "marketing",
    "tags": [
      "advertising & commercial branding"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 5,
    "slug": "perfume-mg-animation-style",
    "title": "Perfume MG Animation Style",
    "category": "Commercial",
    "rawCategory": "Advertising & Commercial Branding",
    "useCase": "Advertising & Commercial Branding",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/perfume-mg-animation-style.mp4",
    "posterSrc": "/media/seedance-1/previews/perfume-mg-animation-style.svg",
    "prompt": "Based on the script from Image 1, generate advertising content for the perfume product in Image 2. The voiceover should reference a natural female voice speaking in English. Pay attention to the proportions of the perfume bottle, integrating it into the background with natural lighting. Avoid heavy texture overlay and cutout effects. The pace can be more brisk.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "marketing",
    "tags": [
      "advertising & commercial branding"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 6,
    "slug": "giant-orange-cat-meme-style",
    "title": "Giant Orange Cat Meme Style",
    "category": "Social",
    "rawCategory": "Social Media & Viral Memes",
    "useCase": "Social Media & Viral Memes",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/giant-orange-cat-meme-style.mp4",
    "posterSrc": "/media/seedance-1/previews/giant-orange-cat-meme-style.svg",
    "prompt": "【Style】Mockumentary, mobile Vlog perspective, hyperrealistic CG combined with real scenes, 8K quality, perfect fur physics simulation.\n【Duration】15 seconds\n【Scene】Hongya Cave in Chongqing or a busy overpass intersection (with magical 8D city feel).\n[00:00-00:05] Shot 1: Visual spectacle (The Reveal).\nThe scene shows a bustling city street. The camera lifts up to reveal a **Gozilla-sized orange tabby cat** stuck between two skyscrapers.\nAction: The giant cat is stuck because it's too fat, waving its huge paws with a pitiful expression, trying to pull itself out.\nDetail: Cat fur is clearly visible in the sunlight, huge paw pads pressing against glass curtain walls, deforming the glass.\n[00:05-00:10] Shot 2: Absurd interaction (The Interaction).\nThe camera switches to ground-level perspective. Traffic flows on the street, traffic lights flashing. The giant cat lowers its head, bringing its huge cat face close to the ground, curiously sniffing a bus waiting at a red light.\nAction: The bus driver calmly reaches out and pets the giant cat's nose. The cat sneezes, instantly blowing away roadside leaves and pedestrians' hats (wind effect).\n[00:10-00:15] Shot 3: Memetic ending (The Punchline).\nThe giant cat finally squeezes past the buildings and sits down on a cross-river bridge, causing the bridge deck to sink slightly (physical feedback).\nNarrative sense: It lazily lies down and starts grooming itself, blocking the entire evening rush hour traffic. The camera finally freezes on its innocent big eyes.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "video",
    "tags": [
      "social media & viral memes"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 7,
    "slug": "surrealistic-documentary-style",
    "title": "Surrealistic Documentary Style",
    "category": "UGC",
    "rawCategory": "UGC Style",
    "useCase": "UGC Style",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/surrealistic-documentary-style.mp4",
    "posterSrc": "/media/seedance-1/previews/surrealistic-documentary-style.svg",
    "prompt": "【Style】Mockumentary (Vlog Style), hyperrealism, fixed-camera real-shot feel, natural lighting, with a slight suspenseful comedy tone.\n【Duration】15 seconds\n【Main Character】An ordinary young beautiful woman, in front of the bathroom sink at home.\n[00:00-00:06] Shot 1: Daily setup (Normalcy).\nScene: In front of a regular bathroom mirror.\nAction: The protagonist is brushing her teeth, mouth full of foam. She makes various funny faces (squinting, eyebrow-wiggling) at the mirror while brushing her teeth.\nKey detail: At this point, the reflection in the mirror is completely normal, movements synchronized.\n[00:06-00:11] Shot 2: BUG appears (The Glitch).\nAction: After brushing teeth, the protagonist lowers her head to spit out foam, then turns around to leave the bathroom.\nHigh-impact moment (core climax): Just as the protagonist's real body has turned and left the mirror frame, the \"reflection\" in the mirror **doesn't move**! That \"reflection\" still maintains the tooth-brushing pose, even mischievously raising eyebrows at the camera with a bad smile, staying for a full 2 seconds, before suddenly panicking and \"fast-forwarding\" to catch up with the original body's movements before disappearing.\nDirector's note: Must create an extremely realistic \"network delay\" feel, as if the reflection has independent consciousness.\n[00:11-00:15] Shot 3: Comedic callback (The Punchline).\nAction: The protagonist, who has already walked to the door, seems to sense something is wrong, suddenly turning back to look at the mirror.\nResult: The mirror has now completely returned to normal, completely empty, only reflecting the opposite wall. The protagonist scratches her head in confusion, showing a life-questioning expression toward the camera. The frame freezes on the protagonist's confused face (comedy effect).",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "video",
    "tags": [
      "ugc style"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 8,
    "slug": "figure-1-vs-figure-2-martial-arts-tournament",
    "title": "Figure 1 vs Figure 2 Martial Arts Tournament",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/figure-1-vs-figure-2-martial-arts-tournament.mp4",
    "posterSrc": "/media/seedance-1/previews/figure-1-vs-figure-2-martial-arts-tournament.svg",
    "prompt": "'Figure 1 character battling Figure 2 character in the World Martial Arts Tournament' with input image",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 9,
    "slug": "nezha-and-ao-bing-ice-fire-clash-space-time-folding",
    "title": "Nezha and Ao Bing Ice-Fire Clash (Space-Time Folding)",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/nezha-and-ao-bing-ice-fire-clash-space-time-folding.mp4",
    "posterSrc": "/media/seedance-1/previews/nezha-and-ao-bing-ice-fire-clash-space-time-folding.svg",
    "prompt": "Act 1: Stillness and Burst (Testing Acceleration from Standstill)\nVisual: Close-up. Nezha's Red Armillary Sash gently sways in the wind with sparks flying. The camera suddenly zooms out rapidly.\nAction: Nezha suddenly kicks off the ground, causing the earth to shatter.\nVisual Focus: Testing Seedance 2.0's simulation of debris trajectory, and the transition from stillness to ultra-high-speed movement.\n\nAct 2: Attribute Transition (Testing Match Cut Editing)\nVisual: Nezha swings his Fire-Tipped Spear in a sweeping motion, creating a circular ring of flames.\nTransition Design: The flame ring seamlessly transforms into Ao Bing's rotating ice blade while spinning.\nAction: The camera follows the rotation axis of the weapons, achieving an instant, smooth transition from red tones to blue tones.\n\nAct 3: Fierce Battle Interaction (Testing Physics Collision and Cinematography)\nVisual: Mid-shot from the side. The Fire-Tipped Spear and ice sword collide in mid-air.\nAction: Sparks and ice fragments explode simultaneously. Ao Bing's body moves like a dragon, spiraling upward around a fire pillar; Nezha inverts in the air, feet-first toward the ground on his Wind-Fire Wheels.\nVisual Focus: Testing whether the model's limbs break down during \"high-speed dueling\" of the two characters.\n\nAct 4: Ultimate Transition (Testing Space Folding)\nVisual: Nezha punches and shatters an ice wall.\nTransition Design: The shattered ice crystals transform into dancing red leaves or fire feathers in the air. The camera passes through the ice fragments and instantly cuts to the next scene.\nVisual Focus: Testing Seedance 2.0's logical continuity using particle continuity.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 10,
    "slug": "otter-mecha-anime-battle-mech-vs-octopus",
    "title": "Otter Mecha Anime Battle (Mech vs. Octopus)",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/otter-mecha-anime-battle-mech-vs-octopus.mp4",
    "posterSrc": "/media/seedance-1/previews/otter-mecha-anime-battle-mech-vs-octopus.svg",
    "prompt": "An anime where an otter goes into a large mech, with lots of quick shots of mechanical parts and gears turning. The otter gives a grim thumbs up, and then pilots the mech, flying into battle against an octopus made of marble.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 11,
    "slug": "tournament-of-power-with-famous-anime-characters",
    "title": "Tournament of Power with Famous Anime Characters",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/tournament-of-power.mp4",
    "posterSrc": "/media/seedance-1/previews/tournament-of-power.svg",
    "prompt": "A massive cosmic arena forms in a blinding void, Tournament-of-Power scale. Crowds from countless universes roar.\nAt the center stands the narrator: Gintoki Sakata, relaxed, wooden sword on his shoulder, bored eyes, sharp tongue.\nHe announces the rules casually, almost mocking fate: \"This tournament decides the strongest. Winner gets a harem.\" Beat. The crowd explodes. Gintoki sighs. \"Yeah, yeah. Don't look at me like that. I didn't write the rules.\"\nThe camera glides to elevated platforms revealing the women of legend, all clearly unimpressed in different ways:\nBulma adjusts her device, already annoyed.\nAndroid 18 crosses her arms, deadpan.\nHinata watches quietly, composed.\nSakura cracks her knuckles.\nNami smiles like she's already planning something.\nBoa Hancock looks away, offended by existence itself.\nMikasa doesn't react. At all.\nErza stands like a judge.\nNico Robin smiles politely—dangerously.\nRukia tilts her head, curious.\n\nGintoki points. \"First match. Try not to destroy the universe before lunch.\"\nTwo tunnels ignite.\n\nFrom the left: Saitama walks out slowly, hands in pockets, face empty. He looks around. \"Huh. This again.\"\nFrom the right: Goku steps forward, serious, focused, sensing something deeply wrong. \"You're strong… but you look like you don't care.\"\nClose-ups alternate. Dust rises. Energy crackles.\nGintoki stands between them.\n\"Alright. Bald guy who's bored versus spiky guy who lives for this.\"\nLights drop.\nPower surges.\nComedy and catastrophe collide.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 12,
    "slug": "motion-graphics",
    "title": "Motion Graphics",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/motion-graphics.mp4",
    "posterSrc": "/media/seedance-1/previews/motion-graphics.svg",
    "prompt": "Create motion graphics animation inspired by traditional animation techniques. Based on the three examples shown, develop an animated sequence that captures the essence of classic animation while leveraging Seedance 2.0's advanced capabilities.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 13,
    "slug": "van-gogh-post-impressionism-style-animation",
    "title": "Van Gogh Post-Impressionism Style Animation",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/van-gogh-animation.mp4",
    "posterSrc": "/media/seedance-1/previews/van-gogh-animation.svg",
    "prompt": "【Style】Van Gogh Post-Impressionism oil painting, thick paint texture (Heavy Impasto), signature swirling brushstrokes, dreamy feel, high saturation blue-yellow contrast.\n【Duration】15 second animation\n[Visual Content] This is a completely dynamic world made of thick oil paint.\nSky: In the deep blue night sky, huge yellow celestial bodies and crescent moon are surrounded by radiating short brushstrokes, nebulae swirling wildly in the air like rushing rivers (Swirling motion).\nForeground: On the left is a huge cypress tree, twisted like burning black flames, shooting up to the sky.\nBackground: A sleeping town in the valley, windows of houses emit warm, circularly painted yellow light. The entire scene slowly flows and breathes following the direction of brushstrokes.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  },
  {
    "id": 14,
    "slug": "luffy-coding-on-macbook-comedy-scene",
    "title": "Luffy Coding on MacBook (Comedy Scene)",
    "category": "Animation",
    "rawCategory": "Anime & Animation Styles",
    "useCase": "Anime & Animation Styles",
    "duration": 15,
    "durationLabel": "15s",
    "aspectRatio": "16:9",
    "videoSrc": "/media/seedance-1/videos/luffy-coding.mp4",
    "posterSrc": "/media/seedance-1/previews/luffy-coding.svg",
    "prompt": "Luffy coding on a Macbook on the Thousand Sunny, RAGING, then throwing it overboard.",
    "featured": false,
    "hero": false,
    "interactive": false,
    "studioTab": "ai-influencer",
    "tags": [
      "anime & animation styles"
    ],
    "sourceUrl": "",
    "sourceRepo": "seedance-1"
  }
];

export const HERO_DEMO_S1 = SEEDANCE_1_DEMOS.find((d) => d.hero);
export const INTERACTIVE_DEMO_S1 = SEEDANCE_1_DEMOS.find((d) => d.interactive);
export const FEATURED_S1 = SEEDANCE_1_DEMOS.filter((d) => d.featured);
